### ISSUE TITLE
Version 0.2.5 is breaking compatibility with flake8<4

### ISSUE THREAD

**Issue by maciej-lech** [peterjc/flake8-black#49]
Hey,

I have noticed that with `flake8==3.9.2` the linter is failing with:
`flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "BLK" due to __init__() got an unexpected keyword argument 'preview'.`

The problem doesn't exist with `flake8-black==0.2.3`. I haven't tested it with `flake8-black==0.2.4` and `flake>=4`

Best regards,
Maciej

**Comment by peterjc** [comment]
Sigh. Do you happen to have the version of black you are using to hand?

**Comment by peterjc** [comment]
Or at least I think that's the problem - trying to reproduce this now.

**Comment by peterjc** [comment]
I've yanked the v0.2.5 release from PyPI (given the nature of this tool that seems wise to pre-empt lots more broken builds).

**Comment by maciej-lech** [comment]
Thank you for your quick response. I have been using `black==21.9b0`

**Comment by peterjc** [comment]
Thanks for confirming - sadly you will have to downgrade flake8-black, or upgrade black.

It was not practical to support both old and new black here.
