### ISSUE TITLE
0.3.1 is not able to open files

### ISSUE THREAD

**Issue by sileht** [peterjc/flake8-black#50]
Hi, looks like last release as an issue with opening files.

For all files flake8-black reports:
```
`BLK999` Unexpected exception: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`
```

**Comment by tommyjcarpenter** [comment]
We also cannot run this on any files due to this issue.

**Comment by peterjc** [comment]
Yanked, newer versions of tomli broke this.

**Comment by peterjc** [comment]
Fixed with v0.3.2, in hindsight I really should have started with fixing #34 today. Sigh.

**Comment by timkpaine** [comment]
@peterjc thanks for the quick fix!

**Comment by peterjc** [comment]
Apologies to you and the other people caught out today. The only bright side is I'd previously learnt the hard way never to schedule a release Friday afternoon (European time), on the off chance it goes wrong. Like today, I broke stuff Friday morning and had Friday afternoon to fix it 😂

**Comment by zyv** [comment]
@peterjc thanks for taking care of this so quickly!

**Comment by timkpaine** [comment]
@peterjc no worries, if you're like me and just pin `>=` then periodic breakages are just a part of life :-)

**Comment by tommyjcarpenter** [comment]
Thank you!
